[build]
  command = "npx expo export:web && node add-sw-registration.js"
  publish = "web-build"

# Redirección para SPA - esto es crucial para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Encabezados específicos para el Service Worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"

# Encabezados para recursos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"